# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:sobiaasim2017@gmail.com}
spring.mail.password=${MAIL_PASSWORD:ayxp armk fcmv osyq}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.application.name=library-management

# Database ? uses environment variables on Railway, localhost for local
spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3306/library_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DATABASE_USERNAME:root}
spring.datasource.password=${DATABASE_PASSWORD:admin123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# App URL
app.frontend.url=${FRONTEND_URL:http://localhost:3000}

# SQL initialization
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true